### PR TITLE
#19 | Handle wallet deeplinks on mobile

### LINKED ISSUE #19: Cannot connect wallet on mobile
**Describe the bug**
Cannot connect to any mobile wallet on mobile browser. It does work using the MetaMask in-app browser as it provides the injected provider. We should only display relevant options and information to the user. 

**To Reproduce**
1. Go to bridge.telos.net
2. Click on 'Connect' (towards bottom of screen)
3. See wallet options
4. See nothing happen on click any option

**Expected behavior**
Should support all visible options (or hide until supported) prioritizing MetaMask to redirect to MetaMask browser or temporarily hide wallet options and provide information to the user directing them to the MM app. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Browser: Chome/Brave

**Related Issue**
- #20

### PR DESCRIPTION
**Pull request by ezra-sg**
# Fixes #19

## Description
This PR updates how the app handles login links, especially on mobile. This includes:
1. removing brave altogether, to be fixed in #20 
2. on mobile, changing login button language to 'Continue on [wallet name]' and opening the selected wallet app when tapped
3. hiding Core wallet entirely on mobile, as they have no deeplink capability

note: at the time of writing, the L0 servers are responding with 500 for the wallet icons. this is happening in prod too, it is not related to this PR

## Test scenarios
- on mobile, install and sign into metamask, coinbase, and phantom apps
- on mobile, go to https://deploy-preview-21--telos-bridge.netlify.app/
- tap "Connect"
    - you should see "Continue on...." + Metamask, coinbase, and phantom
- tap Metamask
    - metamask should open to the bridge application
- go back to bridge in the browser and tap Coinbase
    - coinbase should open to the bridge application
- go back to bridge in the browser and tap phantom
    - the phantom app should open (just to the homepage - dapp deeplinking is not supported)
- on desktop, functionality should be the same as on https://bridge.telos.net

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages
-   [ ] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [x] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test coverage

### CODE REVIEW

File: src/features/bridge/ui/AccountModal.tsx [hunk 1]
```diff
@@ -150,10 +151,50 @@ const InputStateAdornment: React.FC<{type?: 'pending' | 'success' | 'error'}> =
...
+      wallet.connect();
+      return;
+    }
+
+    if (wallet.type === 'MetaMask') {
+      window.open('https://metamask.app.link/dapp/bridge.telos.net');
+    } else if (wallet.type ==='CoinBase') {
+      window.open('https://go.cb-w.com/dapp?cb_url=bridge.telos.net');
+    } else if (wallet.type === 'Phantom') {
+      window.open('https://phantom.app/ul/');
```
Comment (ezra-sg) [inline src/features/bridge/ui/AccountModal.tsx:190]: phantom does not support deeplinking in the way we are doing with MM and coinbase; just open the app in this case

**Review by pmjanus — APPROVED** [review]
Good job ser
